# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0      # LTS
  - 1        # stable
  - nightly  # master
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
   - julia: nightly

## uncomment the following lines to override the default test script

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Currencies")); using Coverage; Codecov.submit(Codecov.process_folder())'
